name: Update Dependencies

on:
  schedule:
    # 定时任务：世界协调时每周一凌晨 00:00
    - cron: "0 0 * * 1"

env:
  TZ: Asia/Shanghai

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Setup .yarnrc.yml
        run: |
          yarn config set nodeLinker node-modules

      - name: Update yarn
        # 更新 Yarn 包管理器自身
        run: yarn set version latest

      - name: Update dependencies
        # 更新 Yarn 项目的所有依赖项
        run: yarn up '*'

      - name: Gather update informations
        id: update_informations
        # 从 Git Diff 中提取本次升级涉及的内容
        run: |
          git diff package.json && echo
          echo "details=$(git diff package.json | grep -e '^[+-] ')" >> $GITHUB_OUTPUT

      - name: Commit and push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 使用上一步提取的更新日志
          message: |
            [Workflows] Update Dependencies

            ${{ steps.update_informations.outputs.details }}
          branch: ${{ github.ref_name }}

      - name: Delete stale workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 4
