name: Update Dependencies

on:
  schedule:
    # 定时任务：世界协调时每周一凌晨 00:00
    - cron: "0 0 * * 1"
  workflow_dispatch:
    # 出错了也能手动去触发

env:
  TZ: Asia/Shanghai

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Setup .yarnrc.yml
        run: yarn config set nodeLinker node-modules

      - name: Update yarn
        # 更新 Yarn 包管理器自身
        run: yarn set version latest

      - name: Update dependencies
        # 更新 Yarn 项目的所有依赖项
        run: yarn up '*'

      - name: Gather update informations
        # 从 Git Diff 中提取本次升级涉及的内容，导出到文件
        run: |
          git diff package.json | grep '^[+-] ' | tee update.log

      - name: Read difference
        # 从指定文件读取内容
        id: get_diff
        uses: juliangruber/read-file-action@v1
        with:
          path: ./update.log

      - name: Commit and push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 使用上一步提取的更新日志
          message: |
            Update Dependencies

            ${{ steps.get_diff.outputs.content }}
          branch: ${{ github.ref_name }}

      - name: Delete stale workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 15
          keep_minimum_runs: 7
